### PR TITLE
Migrate path manager to new VPC

### PR DESCRIPTION
**Pull request by sihil**
This:
- Removes the dynamoDB tables as an external resource
- Renames the stack from composer to flexible
- Introduces a new internal LB for use by intra-VPC apps
- Adds tags to the load balancers
- Migrates to using the machine images repo
- Removes the custom upstart script (use the default one in the machine-images AMI)

TODO:
- [x] Add Retain DeletionPolicy to dynamo tables in existing CFN stacks
- [x] Test in QA by spinning up new path manager in the new VPC
- [x] Switch QA CNAME to complete VPC migration
- [x] Establish how this impacts the path manager dashboard
- [x] Migrate CODE to new VPC
- [x] Migrate RELEASE to new VPC
- [x] Migrate PROD to new VPC

### CODE REVIEW

**Comment by sihil** [comment]
This is now deployed in the QA environment in the new VPC. Would like to verify whether the dashboard is still working before proceeding further.

Would like to hold off merging this until we have migrated the PROD path manager instance to use it.

**Comment by sihil** [comment]
OK - this is all ready to go now. The PROD stack is now up and running and once the CNAME change has been made will be live.

Please review. Intending to flip the CNAME in the morning.

**Comment by steppenwells** [comment]
lets keep the dynamo definition in another file. But otherwise good

:+1:

**Comment by sihil** [comment]
Added definitions as requested.

**Pull request merged**
