### PR TITLE
Add DeletionPolicy = Retain for DynamoDB tables

### PR DESCRIPTION
**Pull request by sihil**

### CODE REVIEW

**Comment by steppenwells** [comment]
looks like it might do what we think, have we tested this?

**Comment by sihil** [comment]
We've used it for S3 buckets in snapshotter and restorer. e.g. https://github.com/guardian/composer-snapshotter/blob/9dd56f129f29cba7100c78f243d30b78655a19cc/cloudformation/snapshotter.json#L72

Will test this in QA. The difficulty is that it reports an error when the only CFN change is a DeletionPolicy change: `Template validation error: No updates are to be performed.`. :unamused:

**Comment by sihil** [comment]
Ultimately I'd like to orphan the existing path manager table from the CFN. But that leaves a question as to how the tables should be initially created in the future. Should the app do it at start up? Or keep it as a separate CFN?

**Comment by sihil** [comment]
Tested and now rolled out in all environments (to prevent any possibility of forgetting to do it later).

**Pull request merged**
